name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install

      - name: Run tests
        run: |
          cd frontend && npm test
          cd ../backend && npm test

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Deploy to server
        run: |
          echo "Deploying application..."